apiVersion: v1
kind: Service
metadata:
  name: linode-db-allowlist
  namespace: linode-db-allowlist
  labels:
    app.kubernetes.io/name: linode-db-allowlist
    app.kubernetes.io/part-of: linode-db-allowlist
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: linode-db-allowlist 