{{- if not .Values.linode.token.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linode-db-allowlist.fullname" . }}-secret
  labels:
    {{- include "linode-db-allowlist.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.linode.token.secretKey }}: {{ .Values.linode.token.value | b64enc | quote }}
{{- end }} 