name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binary
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -v -o bin/linode-db-allowlist-linux-amd64 ./cmd/nodewatcher
          GOOS=darwin GOARCH=amd64 go build -v -o bin/linode-db-allowlist-darwin-amd64 ./cmd/nodewatcher
          GOOS=darwin GOARCH=arm64 go build -v -o bin/linode-db-allowlist-darwin-arm64 ./cmd/nodewatcher
          GOOS=windows GOARCH=amd64 go build -v -o bin/linode-db-allowlist-windows-amd64.exe ./cmd/nodewatcher

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
          failOnError: false
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            bin/linode-db-allowlist-linux-amd64
            bin/linode-db-allowlist-darwin-amd64
            bin/linode-db-allowlist-darwin-arm64
            bin/linode-db-allowlist-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 