name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'deployments/helm/**'
      - '.github/workflows/release-chart.yml'
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  packages: read
  issues: write

jobs:
  release:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Add Helm dependencies repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
        with:
          charts_dir: deployments/helm
          config: .github/cr-config.yml

      - name: Update Helm chart repository index
        run: |
          mkdir -p .cr-release-packages
          helm repo index --url https://bbetter173.github.io/kube-linode-database-controller/deployments/helm/charts .cr-release-packages/
          mv .cr-release-packages/index.yaml index.yaml

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .cr-release-packages
          destination_dir: deployments/helm/charts 